name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Format Terraform code
      - name: Terraform Format
        run: terraform fmt -check

      # Terraform init and plan
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # Execute Bash Script
      - name: Run Cost Optimization Script
        run: |
          chmod +x ./cost_optimization.sh
          ./cost_optimization.sh
